#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

DEB_MIRROR=http://ftp.uk.debian.org/debian
NBD_DEV=/dev/nbd0
BOOT_DEV="$NBD_DEV"p1
ROOT_DEV="$NBD_DEV"p2

# Changing these isn't currently supported
WORKDIR=work
OUTDIR=out
