#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

CURIMG=stage2.qed

. ./common

# For now we add a root user (this is a totally minimal system). It should be 
# disabled at a later stage
configure_users() {
  ssh_in_to_qemu chroot /mnt sh -ex - <<EOF
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
adduser --disabled-password --gecos "" pi
echo "pi:raspberry" | chpasswd
echo "root:root" | chpasswd
EOF
}

configure_fstab() {
  cat <<EOF | sudo tee rootfs/etc/fstab
proc            /proc           proc    defaults          0       0
/dev/mmcblk0p1  /boot           vfat    defaults          0       0
/dev/mmcblk0p2  /               ext4    defaults,noatime  0       0
/dev/mmcblk0p3  none            swap    sw                0       0
EOF
}

configure_sources_list() {
  cat <<EOF | sudo tee rootfs/etc/apt/sources.list
deb $DEB_MIRROR wheezy main non-free
EOF
}

configure_network_interfaces() {
  cat <<EOF | sudo tee rootfs/etc/network/interfaces
auto lo

iface lo inet loopback
iface eth0 inet dhcp
EOF
}

configure_hostname() {
  sudo sh -c "echo raspberrypi > rootfs/etc/hostname" &&
  sudo sh -c 'printf "127.0.1.1\traspberrypi\n" >> rootfs/etc/hosts'
}

download_and_extract_firmware_if_necessary() {
  if ! [ -d firmware ]; then
    git clone git://github.com/raspberrypi/firmware.git
  fi
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage1.qed $CURIMG
dotask run_qemu $CURIMG
dotask configure_users
dotask shutdown_qemu
dotask download_and_extract_firmware_if_necessary
sudo -v
dotask attach_image_to_nbd $CURIMG $NBD_DEV
mkdir -p boot
dotask sudo mount $BOOT_DEV boot
mkdir -p rootfs
dotask sudo mount $ROOT_DEV rootfs
dotask configure_fstab
dotask configure_sources_list
dotask configure_network_interfaces
dotask configure_hostname
dotask sudo cp -a firmware/modules rootfs/lib
dotask sudo cp -a firmware/opt/* rootfs/opt
dotask sudo cp -r firmware/boot/* boot
dotask sudo cp -a boot/arm192_start.elf boot/start.elf # default to 192mb memory split
echo "dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 \
console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait" | sudo tee boot/cmdline.txt
sudo touch rootfs/etc/mtab # let mount handle mtab. TODO: test with df this does as desired
# Don't rename eth0 when we put card in a new board
dotask sudo sed -i -e 's/KERNEL\!="eth\*|/KERNEL\!="/' rootfs/lib/udev/rules.d/75-persistent-net-generator.rules
universal_cleanup
dotask finish_image
