#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

WORKDIR=work
OUTDIR=out
CURIMG=stage4-lxde-edu.qed

. ./common

install_packages() {
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
apt-get update
apt-get install -y python idle python-pygame python-tk
apt-get install -y python3 idle3 python3-tk
apt-get install -y debian-reference-en dillo
EOF
}

install_scratch() {
  onvm_chroot sh -l -e <<\EOF
apt-get install -y scratch
EOF
}

setup_python_game_examples() {
  onvm_chroot sh -l -e <<\EOF
cd /home/pi
wget http://asbradbury.org/tmp/raspi/python_games.tar.gz
tar -xvf python_games.tar.gz
cd python_games
wget http://asbradbury.org/tmp/raspi/fix_wormy.patch
patch -p1 < fix_wormy.patch
rm fix_wormy.patch
wget http://asbradbury.org/tmp/raspi/python_games -O launcher.sh
chmod +x launcher.sh
cd ..
rm python_games.tar.gz
chown -R pi:pi python_games
mkdir -p Desktop
cd Desktop
echo <<EOF1 > python-games.desktop
[Desktop Entry]
Name=Python Games
Comment=From http://inventwithpython.com/pygame/
Exec=/home/pi/python_games/launcher.sh
Icon=/usr/share/pixmaps/python.xpm
Terminal=false
Type=Application
Categories=Application;Games;
StartupNotify=true
EOF1
cd ..
chown -R pi:pi Desktop
EOF
}

# relies on the fact we made a Desktop directory in 
# setup_python_game_examples
setup_desktop_icons() {
  onvm_chroot sh -l -e <<\EOF
cd /usr/share/applications
sudo -u pi cp -a scratch.desktop midori.desktop idle.desktop idle3.desktop \
  lxterminal.desktop debian-reference-common.desktop /home/pi/Desktop
sed -i debian-reference-common.desktop -e "s/^Exec=.*/Exec=env BROWSER=dillo debian-reference/"
EOF
}

# There are 2 menu entries for both of idle3 and idle2. Fix this
hide_redundant_idle_menu_entries() {
  onvm_chroot sh -l -e <<\EOF
mkdir -p /usr/local/share/applications
for ENTRY in /usr/share/applications/idle-python*.desktop; do
  cp -a $ENTRY /usr/local/share/applications
  printf "NoDisplay=true\n" >> "/usr/local/share/applications/$(basename $ENTRY)"
done
EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage4-lxde.qed $CURIMG
dotask run_qemu $CURIMG
dotask disable_starting_services
dotask mount_apt_cache
dotask install_packages
dotask install_scratch
dotask setup_python_game_examples
dotask setup_desktop_icons
dotask hide_redundant_idle_menu_entries
dotask save_space_using_hardlink
dotask allow_starting_services
dotask fingerprint_debian
dotask update_issue
dotask shutdown_qemu
dotask finish_image
