#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

WORKDIR=work
OUTDIR=out
CURIMG=stage4-lxde-edu.qed

. ./common

install_packages() {
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
apt-get update
apt-get install -y python idle python-pygame python-tk
apt-get install -y python3 idle3 python3-tk
EOF
}

install_scratch() {
  download_if_necessary http://asbradbury.org/tmp/raspi/scratch/scratch_1.4.0.1-0miry3_all.deb &&
  scp_in_to_qemu scratch_*.deb /mnt/root &&
  download_if_necessary http://asbradbury.org/tmp/raspi/scratch/scratch-plugins_1.4.0.1-0miry3_armel.deb &&
  scp_in_to_qemu scratch-plugins*.deb /mnt/root &&
  # see http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=471927, scratch is 
  # currently incompatible with wheezy's squeak-vm
  download_if_necessary http://ftp.uk.debian.org/debian/pool/main/s/squeak-vm/squeak-vm_4.0.3.2202-2_armel.deb &&
  scp_in_to_qemu squeak-vm*.deb /mnt/root &&
  
  onvm_chroot sh -l -e <<\EOF
cd /root
dpkg -i squeak*.deb || true
apt-get install -f -y
rm squeak*.deb

# now pin the squeak-vm version
cat <<PINEOF > /etc/apt/preferences.d/squeakpin
Package: squeak-vm
Pin: version 1:4.0*
Pin-Priority: 1001
PINEOF

apt-cache policy squeak-vm # check the pin

# now install scratch and scratch plugins
dpkg -i scratch-plugins*.deb || true
apt-get install -f -y
rm scratch-plugins*.deb

dpkg -i scratch_*.deb || true
apt-get install -f -y
rm scratch_*.deb
EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage4-lxde.qed $CURIMG
dotask run_qemu $CURIMG
dotask disable_starting_services
dotask mount_apt_cache
dotask install_packages
dotask install_scratch
dotask save_space_using_hardlink
dotask allow_starting_services
dotask fingerprint_debian
dotask shutdown_qemu
dotask finish_image
