#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

WORKDIR=work
OUTDIR=out
CURIMG=stage4-lxde-edu.qed

. ./common

install_packages() {
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
apt-get update
apt-get install -y python idle python-pygame python-tk
apt-get install -y python3 idle3 python3-tk
EOF
}

install_scratch() {
  onvm_chroot sh -l -e <<\EOF
apt-get install -y --allow-unauthenticated scratch
EOF
}

setup_python_game_examples() {
  onvm_chroot sh -l -e <<\EOF
cd /home/pi
wget http://asbradbury.org/tmp/raspi/python_games.tar.gz
tar -xvf python_games.tar.gz
rm python_games.tar.gz
chown -R pi:pi python_games
wget http://asbradbury.org/tmp/raspi/python_games
mkdir -p Desktop
chmod +x python_games
mv python_games Desktop
chown -R pi:pi Desktop
EOF
}

# relies on the fact we made a Desktop directory in 
# setup_python_game_examples
setup_desktop_icons() {
  onvm_chroot sh -l -e <<\EOF
cd /usr/share/applications
sudo -u pi cp -a scratch.desktop midori.desktop idle.desktop idle3.desktop /home/pi/Desktop
EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage4-lxde.qed $CURIMG
dotask run_qemu $CURIMG
dotask disable_starting_services
dotask mount_apt_cache
dotask install_packages
dotask install_scratch
dotask setup_python_game_examples
dotask setup_desktop_icons
dotask save_space_using_hardlink
dotask allow_starting_services
dotask fingerprint_debian
dotask update_issue
dotask shutdown_qemu
dotask finish_image
