#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

. ./common

CURIMG=stage4-lxde.$IMGFORMAT

install_packages() {
  # we may want to break out DEBIAN_FRONTEND=noninteractive
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
apt-get update
apt-get install --no-install-recommends -y xserver-xorg-video-fbdev
apt-get install --no-install-recommends -y xserver-xorg xinit
apt-get install --no-install-recommends -y midori
sed -i /etc/xdg/midori/search -e '/duckduckgo.com/s|$|\&t=raspberrypi|'
apt-get install --no-install-recommends -y lxde lxtask menu-xdg gksu
apt-get install -y xpdf gtk2-engines alsa-utils
apt-get install -y --no-install-recommends netsurf-gtk zenity xdg-utils
apt-get install -y desktop-base lxpolkit
apt-get install -y --no-install-recommends gvfs-backends gvfs-fuse
apt-get install -y wpagui
# Install optimised pixman built from https://github.com/bavison/pixman
# TODO: get this properly packaged
cd /tmp
wget http://asbradbury.org/tmp/raspi/libpixman-1.so.0.29.1
cd /usr/lib/arm-linux-gnueabihf
rm libpixman-1.so.0
ln -s libpixman-1.so.0.29.1 libpixman-1.so.0
EOF
}

# make gksu default to sudo mode
configure_gksu() {
  onvm_chroot sh -l -e - <<\EOF
update-alternatives --set libgksu-gconf-defaults /usr/share/libgksu/debian/gconf-defaults.libgksu-sudo
update-gconf-defaults
EOF
}

install_wayland() {
  onvm_chroot sh -l -e - <<\EOF
apt-get update
apt-get install -y libwayland0 libwayland-dev
EOF
}

install_omxplayer() {
  onvm_chroot sh -l -e - <<\EOF
apt-get update
apt-get install -y omxplayer
EOF
}

configure_lxde() {
  onvm_chroot sh -l -e <<\EOF
# first change theme to mist (seems to render noticably faster)
sed /etc/xdg/lxsession/LXDE/desktop.conf -i -e "s|sNet/ThemeName.*|sNet/ThemeName=Mist|"

# configure openbox so it doesn't ask apps to redraw while resizing
sed /etc/xdg/openbox/LXDE/rc.xml -i -e \
  "s|<drawContents>yes</drawContents>|<drawContents>no</drawContents>|"

apt-get install -y raspberrypi-artwork
# change background
update-alternatives --install /usr/share/images/desktop-base/desktop-background \
  desktop-background /usr/share/raspberrypi-artwork/raspberry-pi-logo.png 100
PCMANFMCFG=/etc/xdg/pcmanfm/LXDE/pcmanfm.conf
sed "$PCMANFMCFG" -i -e 's/^wallpaper_mode.*/wallpaper_mode=3/'
sed "$PCMANFMCFG" -i -e 's/^desktop_bg.*/desktop_bg=#ffffff/'

# while we're at it, let's not use xdg-su which Debian doesn't even provide
sed "$PCMANFMCFG" -i -e 's/^su_cmd.*/su_cmd=gksu %s/'
EOF
}

setup_automounting() {
  onvm_chroot sh -l -e <<\EOF1
apt-get install -y udisks
cat <<EOF2 > /etc/polkit-1/localauthority/50-local.d/55-storage.pkla
[Storage Permissions]
Identity=unix-group:plugdev
Action=org.freedesktop.udisks.filesystem-mount;org.freedesktop.udisks.drive-eject;org.freedesktop.udisks.drive-detach;org.freedesktop.udisks.luks-unlock;org.freedesktop.udisks.inhibit-polling;org.freedesktop.udisks.drive-set-spindown
ResultAny=yes
ResultActive=yes
ResultInactive=no
EOF2
EOF1
}

install_and_configure_lightdm() {
  onvm_chroot sh -l -e <<\EOF
apt-get install -y lightdm gnome-themes-standard gnome-icon-theme
update-rc.d lightdm disable 2
sed -i /etc/lightdm/lightdm-gtk-greeter.conf -e "s/^background.*/background=#ffffff/"
# TODO: maybe change the computer icon to the Raspberry Pi logo? See 
# https://wiki.archlinux.org/index.php/LightDM#Changing_the_Icon

# Source /etc/profile and ~/.profile through XSession.d to ensure PATH is set 
# properly when lightdm is used.
cat << EOF1 > /etc/X11/Xsession.d/75source-profile
[ -f /etc/profile ] && . /etc/profile
[ -f "$HOME/.profile" ] && . "$HOME/.profile"
EOF1
EOF
}

install_qt5() {
  onvm_chroot sh -l -e <<\EOF
apt-get update
apt-get install --allow-unauthenticated -y qt50-snapshot qt50-quick-particle-examples
EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage3.$IMGFORMAT $CURIMG
dotask run_qemu $CURIMG
dotask mount_apt_cache
dotask disable_starting_services
#[ -z "$RASPBIAN" ] && dotask install_wayland
dotask install_packages
dotask configure_gksu
[ -n "$RASPBIAN" ] && dotask install_omxplayer
dotask configure_lxde
dotask install_and_configure_lightdm
dotask setup_automounting
#[ -z "$RASPBIAN" ] && dotask install_qt5
dotask save_space_using_hardlink
dotask allow_starting_services
dotask update_issue
dotask fingerprint_debian
dotask shutdown_qemu
dotask finish_image
