#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -e

WORKDIR=work
OUTDIR=out
CURIMG=stage0.qed
NBD_DEV=/dev/nbd0
BOOT_DEV="$NBD_DEV"p1
ROOT_DEV="$NBD_DEV"p2
SWAP_DEV="$NBD_DEV"p3

. ./common

FINISHED_SUCCESSFULLY=0
CLEANED_UP=0

cleanup_atexit() {
  set +e
  if [ $CLEANED_UP -ne 1 ]; then
    printf "Initiating cleanup\n"
    [ -b "$BOOT_DEV" ] && sudo umount $BOOT_DEV
    [ -b "$BOOT_DEV" ] && sudo umount $ROOT_DEV
    [ -b "$NBD_DEV" ] && detach_image_from_nbd $NBD_DEV
  fi
  CLEANED_UP=1
  set -e
}

# Sigh http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=390433
trap 'cleanup_atexit; [ $FINISHED_SUCCESSFULLY -eq 1 ] && printf "Completed successfully\n"' EXIT
trap 'cleanup_atexit; trap - INT; kill -INT $$' INT

create_partition_table() {
  # TODO: partition sizes shouldn't be hard-coded and I should have a swap 
  # partition
  sudo parted $1 <<EOF
  unit mb
  mklabel msdos
  mkpart primary fat32 0 100
  mkpart primary ext4 104 1800
  mkpart primary linux-swap 1800 1900
  print
  quit
EOF
}

do_debootstrap() {
  # TODO: mirror shouldn't be hard-coded
  # Need bzip2 for http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=657560
  sudo debootstrap --components=main,contrib,non-free \
  --verbose \
  --foreign --arch armel --include=bzip2 \
  $1 $2 http://www-uxsup.csx.cam.ac.uk/pub/linux/debian
}

OLDDIR=$(pwd)
mkdir -p $WORKDIR
cd $WORKDIR
[ -b "$NBD_DEV" ] || die "nbd device '%s' does not exist. Try sudo modprobe nbd max_part=16" "$NBD_DEV"
dotask qemu-img create -f qed $CURIMG 1900M
sudo -v
dotask attach_image_to_nbd $CURIMG $NBD_DEV
dotask create_partition_table $NBD_DEV
dotask sudo mkdosfs $BOOT_DEV
dotask sudo mkfs.ext4 -O ^huge_file $ROOT_DEV
dotask sudo mkswap $SWAP_DEV
mkdir -p boot
dotask sudo mount $BOOT_DEV boot
mkdir -p rootfs
dotask sudo mount $ROOT_DEV rootfs
dotask do_debootstrap wheezy rootfs
cleanup_atexit
chmod -w $CURIMG
cd "$OLDDIR"
mkdir -p $OUTDIR
mv $WORKDIR/$CURIMG $OUTDIR
FINISHED_SUCCESSFULLY=1
